### ISSUE TITLE
wrapper script

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#85]
I'd like to wrap the whole weekly procedure in one script to make it really easy on the next librarian/Mike. My plan is to import the /bin scripts I need as modules, and essentially copy-paste the stuff under 'if name==main' into my wrapper script, to run it all in one go.

**Comment by virginiascarlett** [comment]
Already hitting a roadblock:
Traceback (most recent call last):
  File "/groups/scicompsoft/home/scarlettv/dis-utilities/utility/bin/weekly_pubs.py", line 42, in <module>
    update_dois.initialize_program()
  File "/groups/scicompsoft/home/scarlettv/dis-utilities/sync/bin/update_dois.py", line 105, in initialize_program
    if ARG.TARGET == 'dis':
NameError: name 'ARG' is not defined

I think the problem is that this function relies on ARG variables that were defined in the namespace of that running program. A solution would be to rewrite the function to pass ARG.TARGET and ARG.MANIFOLD as command-line args.

**Comment by virginiascarlett** [comment]
Use a shell script instead
